####################################################################################################################################
# Build a local image on the standard clamav image as the pipeline does not want to get the image directly from docker-hub.
####################################################################################################################################
FROM clamav/clamav:stable_base
EXPOSE 3310
