####################################################################################################################################
# Nginx Image
##############################################################################################
FROM nginx:stable
COPY ../resources/nginx/ssl/* /etc/nginx/ssl
COPY ../resources/nginx/nginx.conf.template /etc/nginx/templates/nginx.conf.template
